"use client";

import { useMemo, useState } from "react";
import { Activity, ArrowRight, BookOpen, Box, Braces, Check, ChevronDown, ChevronRight, CircleHelp, Code2, Copy, Download, FileCode2, FileText, Grid2X2, Layers3, LayoutDashboard, LockKeyhole, Menu, Moon, Package, PanelLeft, Search, Settings2, ShieldCheck, Sparkles, Sun, Terminal, X, Zap } from "lucide-react";

type ComponentItem = { name: string; category: string; description: string };
const categories = [
 {name:"Foundation",count:11,icon:"◈",description:"Buttons, typography, badges and essentials."},
 {name:"Forms",count:18,icon:"▤",description:"Inputs, validation and form controls."},
 {name:"Navigation",count:9,icon:"☷",description:"Tabs, menus, breadcrumbs and sidebars."},
 {name:"Data Display",count:13,icon:"▦",description:"Cards, tables, avatars and data views."},
 {name:"Feedback",count:9,icon:"◉",description:"Alerts, dialogs, notifications and toasts."},
 {name:"Layout",count:7,icon:"▣",description:"Grid, stack, flex and spacing tools."},
 {name:"Media",count:4,icon:"▧",description:"Images, video, carousel and cropping."},
 {name:"Overlays",count:4,icon:"▱",description:"Drawers, sheets and command palette."},
 {name:"Charts",count:3,icon:"▥",description:"Bar, pie and donut charts."},
 {name:"Utilities",count:6,icon:"⌘",description:"Focus, portals, copy and accessibility."},
 {name:"Icons",count:1,icon:"✳",description:"Reusable icon exports."}
];
const components:ComponentItem[]=[
 {name:"Button",category:"Foundation",description:"Actions, forms and common interactions."},{name:"IconButton",category:"Foundation",description:"Compact icon-only actions."},{name:"Typography",category:"Foundation",description:"Consistent headings, text and labels."},{name:"Badge",category:"Foundation",description:"Small status labels and counts."},
 {name:"Input",category:"Forms",description:"Text input with configurable states."},{name:"PasswordInput",category:"Forms",description:"Password entry with visibility control."},{name:"Select",category:"Forms",description:"Choose an option from a list."},{name:"Checkbox",category:"Forms",description:"Boolean choices and consent fields."},{name:"OtpInput",category:"Forms",description:"One-time password and PIN entry."},{name:"DatePicker",category:"Forms",description:"Choose a date with a calendar UI."},
 {name:"Card",category:"Data Display",description:"Group related content in a surface."},{name:"Table",category:"Data Display",description:"Organize structured data into rows."},{name:"Avatar",category:"Data Display",description:"Represent a person or account."},{name:"Statistic",category:"Data Display",description:"Highlight a metric or KPI."},
 {name:"Modal",category:"Feedback",description:"Focused tasks and dialog content."},{name:"Alert",category:"Feedback",description:"Communicate important status messages."},{name:"Toast",category:"Feedback",description:"Brief, contextual notifications."},{name:"Tooltip",category:"Feedback",description:"Show helpful information on demand."},
 {name:"Tabs",category:"Navigation",description:"Switch between related content views."},{name:"Sidebar",category:"Navigation",description:"Navigate between app sections."},{name:"Dropdown",category:"Navigation",description:"Actions and options in a menu."},
 {name:"Grid",category:"Layout",description:"Responsive rows and columns."},{name:"Stack",category:"Layout",description:"Arrange content with consistent spacing."},{name:"BarChart",category:"Charts",description:"Compare values across categories."},{name:"ImageCropper",category:"Media",description:"Crop images before saving."},{name:"CommandPalette",category:"Overlays",description:"Keyboard-driven navigation and actions."}
];
const packages=[
 {name:"shivanya-sdk",sub:"Main SDK workspace",version:"0.1.2",desc:"The Shivanya developer ecosystem.",icon:Package,color:"blue"},
 {name:"shivanya-ui",sub:"84 UI components",version:"1.0.6",desc:"Reusable React components and styles.",icon:Grid2X2,color:"indigo"},
 {name:"shivanya-auth",sub:"Authentication",version:"1.0.0",desc:"Login, registration and account UI.",icon:LockKeyhole,color:"purple"},
 {name:"shivanya-core",sub:"Core client",version:"1.0.0",desc:"Shared API client and utilities.",icon:Box,color:"green"},
 {name:"shivanya-shell",sub:"App layouts",version:"1.0.5",desc:"Application shells and page layouts.",icon:PanelLeft,color:"orange"},
 {name:"shivanya-ai",sub:"AI client",version:"0.1.1",desc:"AI client package built on Core.",icon:Sparkles,color:"pink"}
];
function Mark(){return <span className="mark">S</span>}
function Preview({name}:{name:string}) {
 if(name==="Button")return <div className="preview"><button className="btn-demo">Primary button</button><button className="btn-demo outline">Outline</button></div>;
 if(name==="Input")return <div className="preview"><input className="input-demo" placeholder="you@example.com"/></div>;
 if(name==="Card")return <div className="preview"><div className="mini-card"><b>Project overview</b><i/><i/><i/></div></div>;
 if(name==="Modal")return <div className="preview"><div className="mini-modal"><b>Save changes?</b><small>Your updates are ready.</small><button className="btn-demo">Save</button></div></div>;
 if(name==="Dropdown"||name==="Select")return <div className="preview"><button className="select-demo">Choose an option <ChevronDown size={14}/></button></div>;
 if(name==="Table")return <div className="preview"><div className="table-demo"><b>Name　　　　 Status</b><span>Project A　　 Active</span><span>Project B　　 Pending</span></div></div>;
 if(name==="Badge")return <div className="preview"><span className="badge-demo">Active</span><span className="badge-demo purple">New</span></div>;
 if(name==="Alert")return <div className="preview"><div className="alert-demo"><Check size={15}/> Changes saved</div></div>;
 return <div className="preview generic"><span>{name.slice(0,1)}</span><b>{name}</b><small>Component preview</small></div>;
}
export default function Home(){
 const [category,setCategory]=useState("All Components"),[query,setQuery]=useState(""),[tab,setTab]=useState("UI Components"),[selected,setSelected]=useState("Button"),[showAll,setShowAll]=useState(false),[mobile,setMobile]=useState(false),[dark,setDark]=useState(false),[copied,setCopied]=useState(false);
 const filtered=useMemo(()=>components.filter(c=>(category==="All Components"||c.category===category)&&(c.name+" "+c.category+" "+c.description).toLowerCase().includes(query.toLowerCase())),[category,query]);
 const current=components.find(c=>c.name===selected)||components[0];
 const copy=async()=>{try{await navigator.clipboard.writeText("npm install shivanya-ui shivanya-auth shivanya-core shivanya-shell shivanya-ai");setCopied(true);window.setTimeout(()=>setCopied(false),1500)}catch{}};
 const choose=(c:string)=>{setCategory(c);setTab("UI Components");setShowAll(true)};
 return <div className={dark?"site dark":"site"}>
 <header className="topbar"><button className="mobile-menu" onClick={()=>setMobile(!mobile)} aria-label="Menu">{mobile?<X/>:<Menu/>}</button><a className="brand" href="#"><Mark/><b>Shivanya<span>.com</span></b><small>SDK</small></a><label className="global-search"><Search size={16}/><input placeholder="Search components, docs, guides, or anything..." value={query} onChange={e=>{setQuery(e.target.value);setShowAll(true)}}/><kbd>Ctrl K</kbd></label><nav className="top-links"><a href="#docs">Docs</a><a className="active" href="#components">Components</a><a href="#guides">Guides</a><a href="#packages">Packages</a><a href="#playground">Playground</a><a href="#footer">Blog</a></nav><button className="icon-btn" onClick={()=>setDark(!dark)} aria-label="Toggle theme">{dark?<Sun size={17}/>:<Moon size={17}/>}</button><button className="user"><span>A</span> Aditya Thute <ChevronDown size={13}/></button></header>
 <aside className={mobile?"sidebar open":"sidebar"}><div className="side-scroll">
 <a className="side-link active" href="#"><LayoutDashboard size={15}/>Home</a><h5>GET STARTED</h5><a className="side-link" href="#docs"><BookOpen/>Introduction</a><a className="side-link" href="#install"><Download/>Installation</a><a className="side-link" href="#first-app"><Code2/>Create Your First App</a><a className="side-link" href="#structure"><Layers3/>Project Structure</a><a className="side-link" href="#guides"><Zap/>Using Shivanya SDK</a>
 <h5>SHIVANYA PACKAGES <span>6</span></h5><button className="side-link active" onClick={()=>setTab("Packages")}><Package/>All Packages <em>6</em></button>{packages.slice(1).map(p=>{const Icon=p.icon;return <button key={p.name} className="side-link nested" onClick={()=>setTab(p.name)}><Icon size={14}/>{p.name}<em>{p.version}</em></button>})}
 <h5>UI COMPONENTS <span>84</span></h5><button className={category==="All Components"?"side-link active":"side-link"} onClick={()=>choose("All Components")}><Grid2X2/>All Components <em>84</em></button>{categories.map(c=><button key={c.name} className={category===c.name?"side-link active":"side-link"} onClick={()=>choose(c.name)}><span className="cat-symbol">{c.icon}</span>{c.name}<em>›</em></button>)}
 <h5>AUTH · SHIVANYA-AUTH</h5><button className="side-link" onClick={()=>setTab("Authentication")}><ShieldCheck/>Auth overview</button><button className="side-link" onClick={()=>setTab("Authentication")}><LockKeyhole/>Sign in / Sign up</button><button className="side-link" onClick={()=>setTab("Authentication")}><Settings2/>Account management</button>
 <h5>CORE · SHIVANYA-CORE</h5><button className="side-link" onClick={()=>setTab("Core")}><Box/>Client & API</button><button className="side-link" onClick={()=>setTab("Core")}><Activity/>Requests & errors</button>
 <h5>SHELL · SHIVANYA-SHELL</h5><button className="side-link" onClick={()=>setTab("Shell & Layouts")}><PanelLeft/>App shells</button><button className="side-link" onClick={()=>setTab("Shell & Layouts")}><LayoutDashboard/>Dashboard layouts</button>
 <h5>AI · SHIVANYA-AI</h5><button className="side-link" onClick={()=>setTab("AI")}><Sparkles/>AI client</button>
 <div className="help-card"><CircleHelp size={16}/><span>Need help?</span><a href="#guides">Read guides →</a></div></div></aside>
 <main className="main">
 <section className="hero" id="docs"><div className="hero-copy"><div className="eyebrow">● THE SHIVANYA DEVELOPER PLATFORM</div><h1>Build modern web apps<br/><span>with one powerful SDK.</span></h1><p>Beautiful UI components, authentication, core utilities, AI and application shells—designed to work together in your project.</p><div className="hero-actions"><a className="primary" href="#install">Get started <ArrowRight size={15}/></a><a className="secondary" href="#components"><BookOpen size={16}/>Explore components</a></div><div className="install" id="install"><div><Terminal size={13}/> Install packages <button onClick={copy}>{copied?<Check size={14}/>:<Copy size={14}/>}</button></div><code>npm install shivanya-ui shivanya-auth shivanya-core shivanya-shell shivanya-ai</code></div><small className="footnote">Published package versions · See each package's release notes</small></div>
 <div className="hero-preview"><div className="browser"><div className="browser-top"><i/><i/><i/><span>🔒 my-app.local/dashboard</span></div><div className="mock"><aside><b><Mark/> My App</b><label>▦　Dashboard</label><label>▧　Projects</label><label>☷　Tasks</label><label>▥　Analytics</label><label>⚙　Settings</label></aside><div className="mock-body"><header>Overview <span>AT</span></header><div className="stats"><article><small>Total users</small><b>1,248</b><em>↗ 12%</em></article><article><small>Projects</small><b>86</b><em>↗ 8%</em></article><article><small>Revenue</small><b>₹1,24,000</b><em>↗ 20%</em></article></div><div className="chart"><b>Activity overview</b><svg viewBox="0 0 400 100" preserveAspectRatio="none"><path d="M0 78 C40 78 45 35 80 55 S130 82 160 43 S215 59 250 30 S305 54 340 20 S375 29 400 10 L400 100 L0 100Z" fill="#2b7cff20"/><path d="M0 78 C40 78 45 35 80 55 S130 82 160 43 S215 59 250 30 S305 54 340 20 S375 29 400 10" fill="none" stroke="#2478ff" strokeWidth="2.5"/></svg></div><div className="activity"><b>Recent activity</b><span>🟢 Project created <small>2m ago</small></span><span>🔵 Profile updated <small>18m ago</small></span></div></div></div><div className="floating"><Check size={14}/> Reusable. Typed. Ready to build.</div></div></section>
 <section className="package-strip" id="packages">{packages.map(p=>{const Icon=p.icon;return <button key={p.name} className="package-card" onClick={()=>setTab(p.name)}><span className={"package-icon "+p.color}><Icon size={21}/></span><span><b>{p.name}</b><small>{p.sub}</small><p>{p.desc}</p><em>v{p.version}</em></span><ChevronRight className="package-arrow" size={14}/></button>})}</section>
 <div className="tabs">{["UI Components","Authentication","Core","Shell & Layouts","AI","Packages"].map(t=><button key={t} className={tab===t?"selected":""} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==="UI Components"?<section id="components"><div className="section-heading"><div><small>SHIVANYA-UI</small><h2>UI Components <b>84</b></h2><p>Explore the component library by category or search for a component.</p></div><label className="component-search"><Search size={15}/><input placeholder="Search components..." value={query} onChange={e=>{setQuery(e.target.value);setShowAll(true)}}/></label></div>
 <div className="category-grid">{categories.map((c,i)=><button key={c.name} className={category===c.name?"category-card chosen":"category-card"} onClick={()=>choose(c.name)}><span className={"category-icon c"+i}>{c.icon}</span><span><b>{c.name}</b><small>Browse components</small><p>{c.description}</p></span><ArrowRight className="category-arrow" size={13}/></button>)}</div>
 <div className="popular-head"><div><h2>{category==="All Components"?"Popular Components":category+" Components"}</h2><p>Preview a component and explore its usage.</p></div><button className="text-link" onClick={()=>setShowAll(!showAll)}>{showAll?"Show fewer":"View all components"} <ArrowRight size={14}/></button></div>
 {filtered.length?<div className="component-grid">{(showAll?filtered:filtered.slice(0,8)).map(c=><button key={c.name} className={selected===c.name?"component-card chosen":"component-card"} onClick={()=>setSelected(c.name)}><div className="component-tag">{c.category}</div><Preview name={c.name}/><div className="component-info"><b>{c.name}</b><p>{c.description}</p><small>View component <ArrowRight size={12}/></small></div></button>)}</div>:<div className="empty"><Search/><b>No components found</b><button onClick={()=>{setQuery("");setCategory("All Components")}}>Clear filters</button></div>}
 <section className="detail" id="playground"><div className="detail-title"><div><small>COMPONENT REFERENCE</small><h2>{current.name}</h2><p>{current.description}</p></div><span>✓ Published package</span></div><div className="detail-tabs"><button className="selected">Preview</button><button onClick={()=>setTab("Code")}>Code</button><button onClick={()=>setTab("Props")}>Props</button><button onClick={()=>setTab("Examples")}>Examples</button></div><div className="detail-grid"><div className="live"><div className="live-bar">●　●　● <span>Live preview</span></div><Preview name={current.name}/><small>Illustrative preview. Refer to the published API for exact props and behaviour.</small></div><div className="code"><header><FileCode2 size={14}/> Example.tsx <button onClick={copy}>{copied?<Check size={13}/>:<Copy size={13}/>} Copy install</button></header><pre><span>import</span> {"{ "+current.name+" }"} <span>from</span> <i>"shivanya-ui"</i>;{"\n\n"}<span>export default function</span> Example() {"{"}{"\n"}  <span>return</span> ({"\n"}    &lt;{current.name}&gt;{"\n"}      Hello from Shivanya{"\n"}    &lt;/{current.name}&gt;{"\n"}  );{"\n"}{"}"}</pre><footer>✓ TypeScript <small>Check props against your installed version</small></footer></div></div></section>
 </section>:<PackageView tab={tab} onBack={()=>setTab("UI Components")}/>}
 <footer className="footer" id="footer"><div><Mark/><b>Shivanya.com</b><small>Developer tools for building better apps.</small></div><nav><a href="#docs">Documentation</a><a href="#components">Components</a><a href="#packages">Packages</a><a href="#guides">Guides</a><a href="https://github.com/adityathute/shivanya-sdk">GitHub ↗</a></nav><small>© 2026 Shivanya · Built for developers</small></footer>
 </main></div>
}
function PackageView({tab,onBack}:{tab:string;onBack:()=>void}){
 const data:Record<string,{eyebrow:string;title:string;description:string;install:string;features:string[]}>={
 "Authentication":{eyebrow:"SHIVANYA-AUTH",title:"Authentication UI & client",description:"Add sign-in, registration, password recovery and account management to React applications.",install:"npm install shivanya-auth",features:["AuthProvider and useAuth","Login and registration UI","Password reset and email verification","Profile, sessions and security","Cookie and token authentication modes"]},
 "Core":{eyebrow:"SHIVANYA-CORE",title:"Shared platform client",description:"A TypeScript client for making requests to Shivanya platform APIs.",install:"npm install shivanya-core",features:["Typed API client","Request and response helpers","API error handling","Shared platform utilities"]},
 "Shell & Layouts":{eyebrow:"SHIVANYA-SHELL",title:"Application shells and layouts",description:"Build consistent app structures with dashboard, website, centered and blank layouts.",install:"npm install shivanya-shell",features:["DashboardShell and AppShell","Website and centered layouts","PageHeader and PageContainer","Sidebar, header and footer building blocks"]},
 "AI":{eyebrow:"SHIVANYA-AI",title:"AI client",description:"Use the Shivanya AI client package in apps that need platform AI functionality.",install:"npm install shivanya-ai",features:["TypeScript client package","Built on shivanya-core","Package-specific API reference"]},
 "Packages":{eyebrow:"SHIVANYA SDK",title:"Packages for your application",description:"Explore the published package family. Install the modules your app needs; a unified root-package install requires a matching published entry point.",install:"npm install shivanya-ui shivanya-auth shivanya-core shivanya-shell shivanya-ai",features:["shivanya-ui · reusable UI components","shivanya-auth · authentication and account UI","shivanya-core · shared platform client","shivanya-shell · application layouts","shivanya-ai · AI client"]},
 "Code":{eyebrow:"CODE EXAMPLES",title:"Use components in your app",description:"Import components from published package exports and build your own pages.",install:"npm install shivanya-ui",features:["Import public exports","Use TypeScript props","Compose components","Check exact props in package declarations"]},
 "Props":{eyebrow:"API REFERENCE",title:"Component props",description:"Published TypeScript declarations are the authoritative source for component props.",install:"npm install shivanya-ui",features:["TypeScript declarations included","Editor autocomplete","Version-aware examples"]},
 "Examples":{eyebrow:"EXAMPLES",title:"Build with components",description:"Start with a component example and compose it into a complete page.",install:"npm install shivanya-ui",features:["Forms and validation","Dashboard cards and tables","Feedback and overlays","Responsive layout building blocks"]}
 };const d=data[tab]||data.Packages;
 return <section className="package-detail"><div className="package-hero"><small>{d.eyebrow}</small><h2>{d.title}</h2><p>{d.description}</p><code>{d.install}</code></div><div className="package-info"><div><h3>What's included</h3>{d.features.map(f=><p key={f}><Check size={15}/>{f}</p>)}<button className="secondary" onClick={onBack}>Explore UI components <ArrowRight size={14}/></button></div><div><span className="big-icon"><Package size={27}/></span><h3>Designed to work together</h3><p>Use UI, authentication, core client utilities, AI and layouts to build your application.</p><small>✓ TypeScript support　 ·　✓ Published modules</small></div></div><div className="notice"><CircleHelp size={16}/><span><b>Release accuracy</b> Version labels are read from repository metadata and may not reflect the latest npm release. Check npm before publishing documentation.</span></div></section>
}
